### ISSUE TITLE
Device data receiving format

### ISSUE THREAD

**Issue by am-i-abdullah** [Heckie75/govee-h5075-thermo-hygrometer#1]
Hey there, 
I hope you are doing well, and sorry for disturbing you. Can you please share me the documentation of GVH5075 or the format in which you are writing data to the device for reading past recorded data?
I'll be very thankful to you.

Regards

**Comment by Heckie75** [comment]
@am-i-abdullah Pls. take a look at https://github.com/Heckie75/govee-h5075-thermo-hygrometer/blob/main/API.md

On Linux systems you can try these commands 1:1 using the shell tool gatttool.

**Comment by am-i-abdullah** [comment]
Hey thanks a lot, actually I'm using windows and developing an application in flutter (dart). 
Can you please let me know about these handles? as I can't see these in the Characteristics UUIDs.
![image](https://github.com/Heckie75/govee-h5075-thermo-hygrometer/assets/103966950/62edc367-d954-4ed9-b88e-554a48a6d752)

**Comment by Heckie75** [comment]
@am-i-abdullah  Then take a look at https://github.com/Heckie75/govee-h5075-thermo-hygrometer/blob/main/govee-h5075.py line 127ff. There is a static variable called _COMMANDS which is a json object. 

The uuids are:
```json
    _COMMANDS = {
        "NAME": {
            "UUID": "00002a00-0000-1000-8000-00805f9b34fb",
        },
        "FIRMWARE": {
            "UUID": "494e5445-4c4c-495f-524f-434b535f2011",
            "SEQUENCE": [0xaa, 0x0e] + [0] * 17 + [0xa4]
        },
        "HARDWARE": {
            "UUID": "494e5445-4c4c-495f-524f-434b535f2011",
            "SEQUENCE": [0xaa, 0x0d] + [0] * 17 + [0xa7]
        },
        "DATA_CONTROL": {
            "UUID": "494e5445-4c4c-495f-524f-434b535f2012",
            "SEQUENCE": [0x33, 0x01]
        },
        "DATA": {
            "UUID": "494e5445-4c4c-495f-524f-434b535f2013"
        }
    }
```

**Comment by am-i-abdullah** [comment]
yeah, I've seen these. Can you explain me what do you mean by the sequence here?

**Comment by Heckie75** [comment]
@am-i-abdullah The sequence is the payload that is sent, e.g.:
```json
        "FIRMWARE": {
            "UUID": "494e5445-4c4c-495f-524f-434b535f2011",
            "SEQUENCE": [0xaa, 0x0e] + [0] * 17 + [0xa4]
        },
```

is this command:
```
char-write-req 0x11 aa0e0000000000000000000000000000000000a4
```

Of course the handle 0x11 is related to the uuid 494e5445-4c4c-495f-524f-434b535f2011.

**Comment by am-i-abdullah** [comment]
Thanks, can I get GVH5075's official documentation? as I'm receiving these values for a month :) after writing at uuid: 494e5445-4c4c-495f-524f-434b535f2012
I/flutter ( 7482): [238, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 234]
I/flutter ( 7482): ee105000000000000000ea

does it indicates some error?

**Comment by am-i-abdullah** [comment]
always same responses: 

![image](https://github.com/Heckie75/govee-h5075-thermo-hygrometer/assets/103966950/25483e6d-d3c0-4caa-8749-5fdff4f886a2)

**Comment by Heckie75** [comment]
Maybe check the request again. Keep in mind that the thermometer does not keep recorded data if batteries have been removed in the meantime ;-)

**Comment by Heckie75** [comment]
Yes, this is correct as you can see in the example:
```
[A4:C1:38:68:41:23][LE]> char-write-req 0x15 3301001500020000000000000000000000000035
                                             |   |   |   |                         + Byte 20: checksum XORed all bytes from 1 to byte 19 
                                             |   |   |   + Byte 7 - 19: static zeros
                                             |   |   + Byte 5 - 6 (2 bytes): minutes back in the past when to end
                                             |   + Byte 3 - 4 (2 bytes): minutes back in the past when to start
                                             ^ Byte 1 - 2: Command 0x3301

Notification handle = 0x0015 value: 33 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 32
                                    |                                                        + Byte 20: checksum XORed all bytes from 1 to byte 19 
                                    ^ Byte 1 - 2: notification on handle 0x15 that request was successful and data transfer will start
Characteristic value was written successfully

Notification handle = 0x0019 value: 00 15 03 71 e7 03 75 cf 03 71 e7 03 75 cf 03 71 e6 03 75 ce
                                    |     + Byte 3 - 5, 6 - 8, 9 - 11, 12 - 14, 15 - 17, 18 - 20 (6 records each 3 bytes): encoded temperature and humidity (see 'decode temperature and humitity') 
                                    + Byte 1 - 2: minute back of first record, here now - 21m


Notification handle = 0x0019 value: 00 0f 03 75 cf 03 75 cf 03 75 ce 03 75 cf 03 75 ce 03 75 cf
Notification handle = 0x0019 value: 00 09 03 75 cf 03 75 cf 03 75 d1 03 75 d0 03 75 d0 03 75 cf
Notification handle = 0x0019 value: 00 03 03 75 cf 03 75 cf 03 75 ce ff ff ff ff ff ff ff ff ff

Notification handle = 0x0015 value: ee 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 eb
                                    |     |                                                  + Byte 20: checksum XORed all bytes from 1 to byte 19 
                                    |     + Byte 3 - 4: Number of messages (notifications) sent
                                    + Byte 1 - 2: notification on handle 0x15 that data transfer has finished
```

Steps are:
1. Send request with payload on handle 494e5445-4c4c-495f-524f-434b535f2012
2. Get response on handle 494e5445-4c4c-495f-524f-434b535f2012 instantly
3. Get a couple of data notifications on handle 494e5445-4c4c-495f-524f-434b535f2013
4. Get finally a notification on 494e5445-4c4c-495f-524f-434b535f2012 that ends data transmission

**Comment by am-i-abdullah** [comment]
Thanks a lot, should I delete or close this issue?
